# Generated by Django 4.1.7 on 2023-05-08 07:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('figure', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ckeditor_uploader.fields.RichTextUploadingField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nao_Binario')], max_length=1)),
                ('twitter', models.URLField(max_length=50, verbose_name='')),
                ('facebook', models.URLField(max_length=50, verbose_name='')),
                ('instagram', models.URLField(verbose_name='')),
                ('bio', models.TextField(max_length=200)),
                ('hobbies', models.ManyToManyField(to='user.hobbies')),
                ('interest', models.ManyToManyField(to='user.interest')),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personality')),
            ],
        ),
    ]
